Add support for filter spec
databrickslabs/lsql pull request #270
Opened 2024-09-10 05:05 UTC by bishwajit-db

Add support for filter spec.
Add Title and Description for Filters based on filter spec.
Add support for DateRange filter. 
Add support for Filters linked with multiple visualization widgets.

Resolves: #246, #252

2024-09-10 08:38 UTC, JCZuurmond requested changes
@bishwajit-db : Thanks for your contribution! This first iteration functionally looks good. I gave some feedback to move the pieces to the right places. Also, could you add an integration test with a dashboard containing a filter and add a screenshot of the dashboard in the PR?

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +    NONE = "NONE"
When is `None` used?

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +        if not self.dataset_columns:
I think this should be part of the `validate`

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +        config = json.loads(self.content)
Should be part of the `FilterHandler` see `_parse_header` on other Handlers as example

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +        filter_type = FilterType[config.get("type", "MULTI_SELECT").upper()]
`FilterType` conversion from string should happen in the `FilterHandler` during parsing

``` python
        parser.add_argument(
            "--type",
            type=lambda v: WidgetType(v.upper()),
            default=WidgetType.AUTO,
            help=(
                "The widget type to use, see classes with WidgetSpec as parent class in "
                "databricks.labs.lsql.lakeview.model."
            ),
            dest="widget_type",
        )
```

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +            control_encodings.append(ControlFieldEncoding(column, filter_named_query.name, display_name=column))
could you move `ControlFrieldEncoding` to a variable first before appending it the list, like the `NamedQuery` above?

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +            filter_named_query = NamedQuery(name=f"{filter_type}_{column}_{idx}", query=filter_query)
Assuming columns are unique, is the `idx` needed?

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +        spec = filter_spec(encodings=control_encoding_map, frame=frame)
We should test if these are the right encoding for all the filter types

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +    def _filter_tiles_from_folder(cls, folder: Path, query_tiles: Iterable[QueryTile]) -> list[FilterTile]:
Move this logic into `from_tile_metadata`

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +            if not column and not columns:
Should be part of `FilterTile.validate`

2024-09-10 08:38 UTC, JCZuurmond commented on src/databricks/labs/lsql/dashboards.py
> +        for tile in query_tiles:
This flow is different then before:
- Existing: All tiles are treated separately
- New: The filter tile(s) need the queries from the other tiles.

I think we should move this to `get_layouts` where we pass `datasets` to the `get_layouts` of each `Tile`. In the `Tile` we do nothing with the datasets by default, but we use it in the `FilterTile` to build its layouts

2024-09-10 08:43 UTC, bishwajit-db commented on src/databricks/labs/lsql/dashboards.py
> +        metadata.pop("columns", None)
I am not aware. This was present in the spec, so I handled it here. In the implementation, it is being handled as a list with one column.

2024-09-11 17:05 UTC, closed without merging

2024-09-11 17:05 UTC, bishwajit-db commented
Closing this PR and moving to https://github.com/databrickslabs/lsql/pull/276